force-app/main/default/objects/Event_Monitoring_Type__mdt/Event_Monitoring_Type__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to keep values for event monitoring types</description>
    <label>Event Monitoring Type</label>
    <pluralLabel>Event Monitoring Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Monitoring_Type__mdt/fields/Default_Event__c.field-meta.xml
<CustomField>
    <fullName>Default_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Monitoring_Type__mdt/fields/Enabled_To_Admin__c.field-meta.xml
<CustomField>
    <fullName>Enabled_To_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enabled To Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Monitoring_Type__mdt/fields/Enabled_To_Ingest__c.field-meta.xml
<CustomField>
    <fullName>Enabled_To_Ingest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enabled To Ingest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EventMonitoringTypesSelector.cls
public with sharing class EventMonitoringTypesSelector {
    
    public static list<Event_Monitoring_Type__mdt> getAllEventMonitoringTypes() {
       return [SELECT MasterLabel, Enabled_To_Admin__c, Enabled_To_Ingest__c 
               FROM Event_Monitoring_Type__mdt 
               WITH SECURITY_ENFORCED
               ORDER BY MasterLabel];
    }

    public static list<Event_Monitoring_Type__mdt> getEnabledToIngestEventMonitoring() {
        return [SELECT MasterLabel,  Enabled_To_Ingest__c 
                FROM Event_Monitoring_Type__mdt
                WHERE Enabled_To_Ingest__c = true 
                AND Default_Event__c = false
                WITH SECURITY_ENFORCED
                ORDER BY MasterLabel];
    }
}